version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    restart: unless-stopped
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    restart: unless-stopped
