version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    restart: unless-stopped
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    restart: unless-stopped
