{
 "title": "os-1",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "IP", "query": { "query": "label_values(cpu_num,instance)" } },
   { "name": "interval", "label": "平滑区间", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance:.+\",fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_name",
    "label": "展示使用的名称",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",instance=~\"$instance:.+\"}, name)"
    }
   },
   {
    "name": "iid",
    "label": "实例ID",
    "query": {
     "query": "label_values(node_uname_info{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\"},iid)"
    }
   },
   { "name": "sname", "label": "查询" }
  ]
 },
 "panels": [
  {
   "title": "资源总览：（当前选中主机：$instance）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "服务器资源总览表",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "#node_memory_MemTotal_bytes{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} - 0\r\nnode_memory_MemTotal_bytes{} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "#cpu_num{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"} -0 \r\ncpu_num{} -0 ",
     "legendFormat": "总核数"
    },
    {
     "expr": "#load_averange{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\", time=\"5\"}-0\r\nload_averange{time=\"5\"}-0",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 -( avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance) / avg(rate(node_cpu_seconds_total{mode=\"all\"}[$interval])) by (instance))) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemFree_bytes{} / (node_memory_MemTotal_bytes{})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(\r\n    (\r\n        node_filesystem_size_bytes{fstype!=\"\"}#vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}\r\n        -\r\n        node_filesystem_avail_bytes{fstype!=\"\"}#vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}\r\n    ) \r\n    *\r\n        100\r\n    /\r\n        node_filesystem_size_bytes{fstype!=\"\"}#vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\",fstype=~\"ext.?|xfs\"}\r\n)\r\n    by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "# max(rate(node_disk_read_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance)\r\nsum by (instance)(rate(node_disk_read_bytes_total[$interval]))",
     "legendFormat": "最大读取"
    },
    {
     "expr": "#max(rate(node_disk_written_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])) by (instance)\r\nsum by (instance)(rate(node_disk_write_bytes_total[$interval]))",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "#max(rate(node_network_receive_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])*8) by (instance)\r\nsum by (instance) (irate(node_network_receive_bytes_total{}[$interval]))",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "#max(rate(node_network_transmit_bytes_total{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"}[$interval])*8) by (instance)\r\nsum by (instance) (irate(node_network_transmit_bytes_total{}[$interval])) ",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "整体总负载与整体平均CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "#sum(cpu_num{vendor=~\"$vendor\",account=~\"$account\",group=~\"$group\",name=~\"$name\",name=~\".*$sname.*\"})\r\nsum(cpu_num{instance=~\"$instance.*\"})",
     "legendFormat": "cpu线程数"
    },
    {
     "expr": "sum(load_averange{instance=~\"$instance.*\",time=\"1\"})",
     "legendFormat": "总1分钟负载"
    },
    {
     "expr": "sum(load_averange{instance=~\"$instance.*\",time=\"5\"})",
     "legendFormat": "总5分钟负载"
    },
    {
     "expr": "sum(load_averange{instance=~\"$instance.*\",time=\"15\"})",
     "legendFormat": "总15分钟负载"
    },
    {
     "expr": "(1-(avg(increase(node_cpu_seconds_total{instance=~\"$instance.*\",mode=\"idle\"}[$interval])) by (instance) / avg(increase(node_cpu_seconds_total{instance=~\"$instance.*\",mode=\"all\"}[$interval])) by (instance))) * 100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "整体总内存与整体平均内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance.*\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance.*\"} - node_memory_MemFree_bytes{instance=~\"$instance.*\"})",
     "legendFormat": "总已用"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"$instance.*\"} - node_memory_MemFree_bytes{instance=~\"$instance.*\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$instance.*\"}))*100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "整体总磁盘与整体平均磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=~\"$instance.*\"})by(device,instance))",
     "legendFormat": "总磁盘量"
    },
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=~\"$instance.*\"})by(device,instance)) - sum(avg(node_filesystem_avail_bytes{instance=~\"$instance.*\"})by(device,instance))",
     "legendFormat": "总使用量"
    },
    {
     "expr": "(1-sum(avg(node_filesystem_avail_bytes{instance=~\"$instance.*\"})by(device,instance)) / sum(avg(node_filesystem_size_bytes{instance=~\"$instance.*\"})by(device,instance))) * 100",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "资源明细：【$instance】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "【$instance】总体使用率",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "#(1 - ((sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"idle\"}[$interval])) by (instance)) / (sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"all\"}[$interval])) by (instance))) )*100\r\n\r\n(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance.*\",mode=\"idle\"}[$interval])) by (instance) / avg(rate(node_cpu_seconds_total{instance=~\"$instance.*\", mode=\"all\"}[$interval])) by (instance)) * 100+0",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "#(1 - (node_memory_MemFree_bytes{instance=~\"$instance:.+\"} / (node_memory_MemTotal_bytes{instance=~\"$instance:.+\"})))* 100\r\n\r\n(1 - (node_memory_MemFree_bytes{instance=~\"$instance.*\"} / (node_memory_MemTotal_bytes{instance=~\"$instance.*\"})))* 100+0",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "#(node_filesystem_size_bytes{instance=~\"$instance:.+\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_avail_bytes{instance=~\"$instance:.+\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_size_bytes{instance=~\"$instance:.+\",fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})\r\n(node_filesystem_size_bytes{instance=~\"$instance.*\",fstype!=\"\"}-node_filesystem_avail_bytes{instance=~\"$instance.*\",fstype!=\"\"})*100 /(node_filesystem_size_bytes{instance=~\"$instance.*\",fstype!=\"\"})+0",
     "legendFormat": "分区({{mountpoint}})使用率"
    }
   ]
  },
  {
   "title": "【$instance】各分区可用空间",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "#node_filesystem_size_bytes{instance=~\"$instance:.+\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0\r\n#node_filesystem_size_bytes{instance=~\"$instance.*\",mountpoint !~\".*pod.*\"}-0\r\nnode_filesystem_size_bytes{instance=~\"$instance:.+\", fstype!=\"\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "#node_filesystem_avail_bytes{instance=~\"$instance.*\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-0\r\n#node_filesystem_avail_bytes{instance=~\"$instance:.+\",mountpoint !~\".*pod.*\"}-0\r\nnode_filesystem_avail_bytes{instance=~\"$instance:.+\", fstype!=\"\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"$instance.*\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}-node_filesystem_avail_bytes{instance=~\"$instance.*\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_size_bytes{instance=~\"$instance.*\",fstype=~\"ext.*|xfs|nfs\",mountpoint !~\".*pod.*\"})\r\n#(node_filesystem_size_bytes{instance=~\"$instance:.+\",mountpoint !~\".*pod.*\"}-node_filesystem_avail_bytes{instance=~\"$instance:.+\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_size_bytes{instance=~\"$instance:.+\",mountpoint !~\".*pod.*\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "core_num{instance=~\"$instance:.+\"}",
     "legendFormat": "CPU 核数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cpu_num{instance=~\"$instance:.+\"}",
     "legendFormat": "CPU 线程数",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance:.+\"})",
     "legendFormat": "总内存",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "【$instance】CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"system\"}[$interval])) by (instance)) / (sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"all\"}[$interval])) by (instance))) )*100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "(((sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"user\"}[$interval])) by (instance)) / (sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"all\"}[$interval])) by (instance))) )*100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "(((sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"iowait\"}[$interval])) by (instance)) / (sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"all\"}[$interval])) by (instance))) )*100",
     "legendFormat": "IOwait使用率"
    },
    {
     "expr": "(1 - ((sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"idle\"}[$interval])) by (instance)) / (sum(increase(node_cpu_seconds_total{instance=~\"$instance:.+\",mode=\"all\"}[$interval])) by (instance))) )*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "【$instance】内存信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance.*\"} - node_memory_MemFree_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "可用"
    },
    {
     "expr": "(1 - (node_memory_MemFree_bytes{instance=~\"$instance.*\"} / (node_memory_MemTotal_bytes{instance=~\"$instance.*\"})))* 100",
     "legendFormat": "使用率"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "Buffer内存大小"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "Cached内存大小"
    }
   ]
  },
  {
   "title": "【$instance】虚存使用前十进程信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "使用量" }
   ],
   "targets": [
    {
     "expr": "topk(10,(node_process_virtual_memory_bytes{instance=~\"$instance:.+\"}))",
     "legendFormat": "进程{{pid}}虚存使用量"
    }
   ]
  },
  {
   "title": "【$instance】系统平均负载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "load_averange{instance=~\"$instance:.+\"}",
     "legendFormat": "{{time}}分钟负载"
    },
    {
     "expr": "cpu_num{instance=~\"$instance:.+\"}",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "【$instance】进程运行状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_total{instance=~\"$instance:.+\"}",
     "legendFormat": "进程总数",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=~\"$instance:.+\"}",
     "legendFormat": "运行态的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=~\"$instance:.+\"}",
     "legendFormat": "等待IO完成阻塞的进程",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Binstance%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "【$instance】磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-(node_filesystem_avail_bytes{instance=~\"$instance:.+\",fstype!=\"\"})/(node_filesystem_size_bytes{instance=~\"$instance:.+\"}))*100",
     "legendFormat": "容量%：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "【$instance】每秒磁盘读写容量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "磁盘{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_write_bytes_total{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "磁盘{{device}}_写入"
    }
   ]
  },
  {
   "title": "【$instance】磁盘读写速率（IOPS）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "磁盘{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "磁盘{{device}}_写入"
    }
   ]
  },
  {
   "title": "【$instance】每分钟流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "#increase(node_network_receive_bytes_total{instance=~\"$instance:.+\",device=~\"$device\"}[1m])\r\nincrease(node_network_receive_bytes_total{instance=~\"$instance:.+\"}[1m])",
     "legendFormat": "{{device}}_下载"
    },
    {
     "expr": "#increase(node_network_transmit_bytes_total{instance=~\"$instance:.+\",device=~\"$device\"}[1m])\r\nincrease(node_network_transmit_bytes_total{instance=~\"$instance:.+\"}[1m])",
     "legendFormat": "{{device}}_上传"
    }
   ]
  },
  {
   "title": "【$instance】网络Socket连接信息",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance:.+\"} + 0",
     "legendFormat": "TCP连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$instance:.+\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"$instance:.+\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"$instance:.+\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$instance:.+\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_PassiveOpens{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "{{instance}}_Tcp_PassiveOpens"
    },
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "{{instance}}_Tcp_ActiveOpens"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~\"$instance:.+\"}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    },
    {
     "expr": "rate(node_netstat_TcpExt_ListenDrops{instance=~\"$instance:.+\"}[$interval])"
    }
   ]
  },
  {
   "title": "【$instance】网络带宽",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "#rate(node_network_receive_bytes_total{instance=~\"$instance:.+\",device=~\"$device\"}[$interval])*8\r\nrate(node_network_receive_bytes_total{instance=~\"$instance:.+\"}[$interval])*8 - 0",
     "legendFormat": "网卡{{device}}_下载"
    },
    {
     "expr": "#rate(node_network_transmit_bytes_total{instance=~\"$instance:.+\",device=~\"$device\"}[$interval])*8\r\nrate(node_network_receive_bytes_total{instance=~\"$instance:.+\"}[$interval])*8 + 0",
     "legendFormat": "网卡{{device}}_上传"
    }
   ]
  },
  {
   "title": "【$instance】Cache容量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cache_L1_max_size_bype{instance=~\"$instance.*\"}",
     "legendFormat": "L1",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cache_L2_max_size_bype{instance=~\"$instance.*\"}",
     "legendFormat": "L2",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "cache_L3_max_size_bype{instance=~\"$instance.*\"}",
     "legendFormat": "L3",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "【$instance】Cache命中率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 56 },
   "targets": [
    {
     "expr": "cache_L1_miss_rate{instance=~\"$instance.*\"}",
     "legendFormat": "L1cache未命中率"
    },
    {
     "expr": "cache_L2_miss_rate{instance=~\"$instance.*\"}",
     "legendFormat": "L2cache未命中率"
    },
    {
     "expr": "cache_L3_miss_rate{instance=~\"$instance.*\"}",
     "legendFormat": "L3cache未命中率"
    }
   ]
  },
  {
   "title": "【$instance】系统IPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 56 },
   "targets": [
    {
     "expr": "system_ipc{instance=~\"$instance.*\"}",
     "legendFormat": "IPC"
    }
   ]
  }
 ]
}